# HW 5 -  Data types, strings, and GroupBy
ANALYST: Fan Li

DUE DATE: Nov 17, 2020

PURPOSE: To complete data type, strings and groupby operation.

###### SETUPS

In [1]:
# import libraries
import numpy as np
import pandas as pd

In [2]:
# read in datasets with the ID column set to be the index value
fifa=pd.read_csv("../../data/fifa19_ver1.csv",index_col='ID')
fifa.head()

,Name,Age,Photo,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Body Type,Position,Jersey Number
ID,,,,,,,,,,,,,,,,
158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,94,94,FC Barcelona,€110.5M,€565K,Left,5.0,4.0,4.0,Messi,RF,10.0
20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,94,94,Juventus,€77M,€405K,Right,5.0,4.0,5.0,C. Ronaldo,ST,7.0
190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Right,5.0,5.0,5.0,Neymar,LW,10.0
193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,91,93,Manchester United,€72M,€260K,Right,4.0,3.0,1.0,Lean,GK,1.0
192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,91,92,Manchester City,€102M,€355K,Right,4.0,5.0,4.0,Normal,RCM,7.0

###### Part 1

In [3]:
fifa.dtypes

Name                         object
Age                           int64
Photo                        object
Nationality                  object
Overall                       int64
Potential                     int64
Club                         object
Value                        object
Wage                         object
Preferred Foot               object
International Reputation    float64
Weak Foot                   float64
Skill Moves                 float64
Body Type                    object
Position                     object
Jersey Number               float64
dtype: object

In [4]:
# Photo
fifa['player_photo']=fifa['Photo'].str.split("https://cdn.sofifa.org/players/4/19/").str[1]
fifa.drop('Photo',axis=1,inplace=True)

In [5]:
fifa.head()

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Body Type,Position,Jersey Number,player_photo
ID,,,,,,,,,,,,,,,,
158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Left,5.0,4.0,4.0,Messi,RF,10.0,158023.png
20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Right,5.0,4.0,5.0,C. Ronaldo,ST,7.0,20801.png
190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Right,5.0,5.0,5.0,Neymar,LW,10.0,190871.png
193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Right,4.0,3.0,1.0,Lean,GK,1.0,193080.png
192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Right,4.0,5.0,4.0,Normal,RCM,7.0,192985.png

In [6]:
# Wage
fifa['wage_euros']=fifa['Wage'].replace({'€':"",'K':""},regex=True).str.strip().astype(float)
fifa.drop('Wage',axis=1,inplace=True)
fifa.head()

,Name,Age,Nationality,Overall,Potential,Club,Value,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Body Type,Position,Jersey Number,player_photo,wage_euros
ID,,,,,,,,,,,,,,,,
158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,Left,5.0,4.0,4.0,Messi,RF,10.0,158023.png,565.0
20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,Right,5.0,4.0,5.0,C. Ronaldo,ST,7.0,20801.png,405.0
190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,Right,5.0,5.0,5.0,Neymar,LW,10.0,190871.png,290.0
193080,De Gea,27,Spain,91,93,Manchester United,€72M,Right,4.0,3.0,1.0,Lean,GK,1.0,193080.png,260.0
192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,Right,4.0,5.0,4.0,Normal,RCM,7.0,192985.png,355.0

In [7]:
fifa.dtypes

Name                         object
Age                           int64
Nationality                  object
Overall                       int64
Potential                     int64
Club                         object
Value                        object
Preferred Foot               object
International Reputation    float64
Weak Foot                   float64
Skill Moves                 float64
Body Type                    object
Position                     object
Jersey Number               float64
player_photo                 object
wage_euros                  float64
dtype: object

In [8]:
# category columns
fifa[list(fifa)[7:11]]=fifa[list(fifa)[7:11]].astype("category")
fifa.dtypes

Name                          object
Age                            int64
Nationality                   object
Overall                        int64
Potential                      int64
Club                          object
Value                         object
Preferred Foot              category
International Reputation    category
Weak Foot                   category
Skill Moves                 category
Body Type                     object
Position                      object
Jersey Number                float64
player_photo                  object
wage_euros                   float64
dtype: object

In [9]:
# Jersey Number
fifa['Jersey Number'].fillna(0,inplace=True)
fifa['Jersey Number']=fifa['Jersey Number'].astype(int).astype(str)

In [10]:
fifa.head()

,Name,Age,Nationality,Overall,Potential,Club,Value,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Body Type,Position,Jersey Number,player_photo,wage_euros
ID,,,,,,,,,,,,,,,,
158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,Left,5.0,4.0,4.0,Messi,RF,10,158023.png,565.0
20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,Right,5.0,4.0,5.0,C. Ronaldo,ST,7,20801.png,405.0
190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,Right,5.0,5.0,5.0,Neymar,LW,10,190871.png,290.0
193080,De Gea,27,Spain,91,93,Manchester United,€72M,Right,4.0,3.0,1.0,Lean,GK,1,193080.png,260.0
192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,Right,4.0,5.0,4.0,Normal,RCM,7,192985.png,355.0

In [11]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18207 entries, 158023 to 246269
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      18207 non-null  object
 1   Age                       18207 non-null  int64
 2   Nationality               18207 non-null  object
 3   Overall                   18207 non-null  int64
 4   Potential                 18207 non-null  int64
 5   Club                      17966 non-null  object
 6   Value                     18207 non-null  object
 7   Preferred Foot            18159 non-null  category
 8   International Reputation  18159 non-null  category
 9   Weak Foot                 18159 non-null  category
 10  Skill Moves               18159 non-null  category
 11  Body Type                 18159 non-null  object
 12  Position                  18147 non-null  object
 13  Jersey Number             18207 non-null  object
 14  player_photo              18207 non-null  object
 15  wage_euros                18207 non-null  float64
dtypes: category(4), float64(1), int64(3), object(8)
memory usage: 1.9+ MB

###### Part 2

In [12]:
# 1. How many players are left footed?
print(fifa.groupby('Preferred Foot')['Preferred Foot'].count(),'\n',
     "4211 players are left footed")

Preferred Foot
Left      4211
Right    13948
Name: Preferred Foot, dtype: int64
 4211 players are left footed

In [13]:
# 2. Which clubs have the three highest weekly payroll totals?
print(fifa.groupby('Club')['wage_euros'].sum().nlargest(3),'\n',
     "Clubs have the three highest weekly payroll totals are: Real Madrid, FC Barcelona, Manchester City")

Club
Real Madrid        5017.0
FC Barcelona       4837.0
Manchester City    3741.0
Name: wage_euros, dtype: float64
 Clubs have the three highest weekly payroll totals are: Real Madrid, FC Barcelona, Manchester City

In [14]:
# 3. What are the five most common jersey numbers?
print(fifa.groupby('Jersey Number')['Jersey Number'].count().nlargest(5),'\n',
     "The five most common jersey numbers are 8,7,10,11,6")

Jersey Number
8     612
7     604
10    593
11    590
6     586
Name: Jersey Number, dtype: int64
 The five most common jersey numbers are 8,7,10,11,6

In [15]:
# 4. Players from which country (i.e., “Nationality”) have the lowest average age?
print(fifa.groupby('Nationality')['Age'].mean().nsmallest(1),'\n',
      "Players from Indonesia have the lowest average age")

Nationality
Indonesia    17.0
Name: Age, dtype: float64
 Players from Indonesia have the lowest average age